### ISSUE TITLE
Резервы

### ISSUE THREAD

**Issue by tatyanavolkova** [old-bibigon/parse-cik#2]
Очень хотелось бы получить возможность скачивать резервы избирательных комиссий.
На сайте вроде бы есть такой раздел, там всё аналогично:
http://www.vybory.izbirkom.ru/moscow_city/ik_r_tree/
Но у меня пока не получилось переделать код, чтобы скачать резервы :(

**Comment by tatyanavolkova** [comment]
По Костроме резервы не скачиваются :(

$ python down.py --with-reserve --region=kostromaTraceback (most recent call last):
  File "down.py", line 54, in <module>
    vals = ik.parse_reserve(recursion=True)
  File "/home/tatyana/Documents/ELECTIONS/СоставыКомиссий/parse-cik-master/cik.py", line 215, in parse_reserve
    self.parse_reserve_childs(recursion)
  File "/home/tatyana/Documents/ELECTIONS/СоставыКомиссий/parse-cik-master/cik.py", line 329, in parse_reserve_childs
    found_ik.parse_reserve(recursion)
  File "/home/tatyana/Documents/ELECTIONS/СоставыКомиссий/parse-cik-master/cik.py", line 215, in parse_reserve
    self.parse_reserve_childs(recursion)
  File "/home/tatyana/Documents/ELECTIONS/СоставыКомиссий/parse-cik-master/cik.py", line 329, in parse_reserve_childs
    found_ik.parse_reserve(recursion)
  File "/home/tatyana/Documents/ELECTIONS/СоставыКомиссий/parse-cik-master/cik.py", line 206, in parse_reserve
    ehtml = lxml.html.fromstring(data_reserv)
  File "/usr/lib/python2.7/dist-packages/lxml/html/__init__.py", line 704, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/lib/python2.7/dist-packages/lxml/html/__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68106)
  File "parser.pxi", line 1785, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102455)
  File "parser.pxi", line 1666, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101214)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96124)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91889)
lxml.etree.XMLSyntaxError: line 87: Tag nobr invalid

**Comment by tatyanavolkova** [comment]
По Новосибу резервы скачиваются, но там та проблема, о которой писали выше - у резервников указан id ТИКа, а не УИКа :(

**Comment by old-bibigon** [comment]
Только сейчас проверил Кострому - нормально скачалось.
Это, возможно, проблемы с инетом были - как-то скачался не полный файл, удалите из orig/kostroma или всё или что-нибудь выборочно (последний файл по дате или все *_reserve*) и перекачайте. Скрипт смотрит есть ли файл в orig и не перекачивает его снова.
С -v скрипт становится более болтливым, и вы хотя бы номер УИК будете знать где он встал.
