### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kalenkov** [old-bibigon/parse-cik#7]
Видимо что-то поменяли в верстке страниц

запуск скрипта
_python down.py_
заканчивается ошибкой
```Traceback (most recent call last):
  File "down.py", line 50, in <module>
    vals = ik.parse(recursion=True)
  File "/home/mkalenkov/Download/parse-cik-master/cik.py", line 197, in parse
    div_main = ehtml.xpath('//div[@id="main"]/*/div[@class="center-colm"]')[0]
IndexError: list index out of range
```

**Comment by old-bibigon** [comment]
Скорее всего, интернет барахлил - в кеш неправильная страниц упала.
