### ISSUE TITLE
Ошибки при скачивании

### ISSUE THREAD

**Issue by kalenkov** [old-bibigon/parse-cik#8]
При запуске скрипта начинают валиться ошибки в большом количестве. Иногда надо немного подождать, чтобы ошибки появились

```
ERROR:root:Ошибка при загрузке Участковая избирательная комиссия №1690 (bashkortostan) из http://www.bashkortostan.vybory.izbirkom.ru/region/bashkortostan?action=ik&vrn=4024020171276
Traceback (most recent call last):
  File "/home/mkalenkov/temp/cik/parse-cik-master/cik.py", line 260, in parse
    self.parse_data(data, update, recursion)
  File "/home/mkalenkov/temp/cik/parse-cik-master/cik.py", line 205, in parse_data
    ehtml = lxml.html.fromstring(data)
  File "/usr/lib64/python2.7/site-packages/lxml/html/__init__.py", line 876, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/lib64/python2.7/site-packages/lxml/html/__init__.py", line 765, in document_fromstring
    "Document is empty")
ParserError: Document is empty
ERROR:root:Not download http://www.bashkortostan.vybory.izbirkom.ru/region/bashkortostan?action=ik&vrn=4024020171331
Traceback (most recent call last):
  File "/home/mkalenkov/temp/cik/parse-cik-master/cik.py", line 115, in down_data
    data = urllib.urlopen(url).read()
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
```

Вроде жалуется на невозможность скачать страницу. Но в браузере они открываются без проблем.

**Comment by old-bibigon** [comment]
умвр, только что посмотрел.
запустите ещё раз без очистки кеша в orig/, перекачать должен

**Comment by kalenkov** [comment]
Да, всё работает. Видимо планеты тогда не так стояли.
